# Generated by Django 5.2.6 on 2026-09-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('pays', models.CharField(blank=True, max_length=40)),
                ('ordre', models.PositiveSmallIntegerField(default=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('nom_court', models.CharField(max_length=24)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coup_denvoi', models.DateTimeField(db_index=True)),
                ('journee', models.CharField(blank=True, max_length=40)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('reporte', 'Reporté')], default='a_venir', max_length=10)),
                ('buts_dom', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buts_ext', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buts_dom_mt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buts_ext_mt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchs', to='paris.competition')),
                ('domicile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='paris.equipe')),
                ('exterieur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='paris.equipe')),
            ],
            options={
                'ordering': ['coup_denvoi'],
            },
        ),
        migrations.CreateModel(
            name='Cote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=40)),
                ('marche', models.CharField(max_length=20)),
                ('selection', models.CharField(max_length=20)),
                ('valeur', models.DecimalField(decimal_places=3, max_digits=7)),
                ('nb_sources', models.PositiveSmallIntegerField(default=1)),
                ('releve_le', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotes', to='paris.match')),
            ],
        ),
        migrations.CreateModel(
            name='Contexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme_dom', models.TextField(blank=True)),
                ('forme_ext', models.TextField(blank=True)),
                ('absents_dom', models.TextField(blank=True)),
                ('absents_ext', models.TextField(blank=True)),
                ('tendance_buts', models.TextField(blank=True)),
                ('a_savoir', models.TextField(blank=True)),
                ('confrontations', models.TextField(blank=True)),
                ('fiabilite', models.CharField(default='moyenne', max_length=8)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contexte', to='paris.match')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buts_dom_attendus', models.FloatField()),
                ('buts_ext_attendus', models.FloatField()),
                ('p1', models.FloatField()),
                ('pn', models.FloatField()),
                ('p2', models.FloatField()),
                ('score_probable', models.CharField(max_length=8)),
                ('profil', models.CharField(max_length=16)),
                ('marge_marche', models.FloatField()),
                ('residu', models.FloatField()),
                ('version_moteur', models.CharField(max_length=12)),
                ('calcule_le', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='paris.match')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('libelle', models.CharField(max_length=120)),
                ('probabilite', models.FloatField()),
                ('cote_juste', models.FloatField()),
                ('niveau', models.CharField(choices=[('prudente', 'Prudente'), ('equilibree', 'Équilibrée'), ('audacieuse', 'Audacieuse'), ('filet', 'Filet de sécurité'), ('detail', 'Détail')], default='detail', max_length=12)),
                ('origine', models.CharField(choices=[('marche', 'Marché'), ('calcul', 'Calculé')], max_length=8)),
                ('resultat', models.CharField(choices=[('attente', 'En attente'), ('gagne', 'Gagné'), ('perdu', 'Perdu'), ('annule', 'Annulé')], default='attente', max_length=8)),
                ('regle_le', models.DateTimeField(blank=True, null=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='paris.analyse')),
            ],
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['statut', 'coup_denvoi'], name='paris_match_statut_0df0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition', 'coup_denvoi'], name='paris_match_competi_55f0ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('domicile', 'exterieur', 'coup_denvoi'), name='match_unique'),
        ),
        migrations.AddIndex(
            model_name='cote',
            index=models.Index(fields=['match', 'marche'], name='paris_cote_match_i_edd1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['niveau', 'resultat'], name='paris_optio_niveau_4bb9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['famille', 'resultat'], name='paris_optio_famille_9df622_idx'),
        ),
    ]
