# Generated by Django 5.2.6 on 2026-09-08 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sofascore_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='sofascore_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sofascore_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PropositionParis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=160)),
                ('confiance', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='paris.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='paris.propositionparis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proposition', 'user'), name='vote_unique_user_prop')],
            },
        ),
    ]
