# Generated by Django 5.2.6 on 2026-09-09 22:55

from django.db import migrations, models
from django.utils import timezone


def remplir_expiration_vip(apps, schema_editor):
    """VIP existants : expiration = activation + 1 mois (ou maintenant + 1 mois)."""
    from paris.vip import ajouter_mois

    Profil = apps.get_model('paris', 'Profil')
    for p in Profil.objects.filter(categorie__in=('vip', 'premium'), vip_expire_le__isnull=True):
        base = p.vip_depuis or timezone.now()
        p.vip_expire_le = ajouter_mois(base, 1)
        if not p.vip_depuis:
            p.vip_depuis = base
        p.save(update_fields=['vip_expire_le', 'vip_depuis'])


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0006_reglagesite_vip_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyse',
            options={'verbose_name': 'Analyse moteur', 'verbose_name_plural': 'Analyses moteur'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Compétition', 'verbose_name_plural': 'Compétitions'},
        ),
        migrations.AlterModelOptions(
            name='contexte',
            options={'verbose_name': 'Contexte match', 'verbose_name_plural': 'Contextes match'},
        ),
        migrations.AlterModelOptions(
            name='cote',
            options={'verbose_name': 'Cote', 'verbose_name_plural': 'Cotes'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Équipe', 'verbose_name_plural': 'Équipes'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['coup_denvoi'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Tip / option', 'verbose_name_plural': 'Tips / options'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='propositionparis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proposition utilisateur', 'verbose_name_plural': 'Propositions utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote proposition', 'verbose_name_plural': 'Votes propositions'},
        ),
        migrations.AlterModelOptions(
            name='voteoption',
            options={'verbose_name': 'Vote tip', 'verbose_name_plural': 'Votes tips'},
        ),
        migrations.AddField(
            model_name='profil',
            name='vip_expire_le',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fin d’abonnement (en général +1 mois après validation). Editable pour prolonger.', null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='vip_depuis',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière activation VIP.', null=True),
        ),
        migrations.RunPython(remplir_expiration_vip, migrations.RunPython.noop),
    ]
